### ISSUE TITLE
makedist.sh

### ISSUE THREAD

**Issue by redboltz** [ygj6/msgpack-c#4]
https://github.com/msgpack/msgpack-c/releases
When I release msgpack-c, I use makedist.sh.
It creates release tarball e.g.) msgpack-3.2.1.tar.gz.

After C and C++ separate, makedist.sh should different prefix.

I have a following idea:

For C,

```
prefix=msgpack-c-$ver
```

For C++

```
prefix=msgpack-cxx-$ver
```

NOTE

The reason I chose cxx instead of cpp, there are some exisiting msgpack-cpp projects https://github.com/search?q=msgpack-cpp .
There is no msgpack-cxx projects, so far https://github.com/search?q=msgpack-cxx

**Comment by ygj6** [comment]
Has been modified. Thanks.
